value = input('Digite algo: ')
print('O valor digitado foi: ', value)
print('O tipo primitivo desse valor é: ', type(value))
print('Só tem espaços? ', value.isspace())
print('É um número? ', value.isnumeric())
print('É alfabético? ', value.isalpha())
print('É alfanumérico? ', value.isalnum())
print('Está em maiúsculas? ', value.isupper())
print('Está em minúsculas? ', value.islower())
print('Está capitalizada? ', value.istitle())
print('É um dígito? ', value.isdigit())
print('É um identificador? ', value.isidentifier())
print('É um decimal? ', value.isdecimal())
